### ISSUE TITLE
Iffley measurements unreliable - solution?

### ISSUE THREAD

**Issue by docpopi** [jamtholee/flags#14]
Hi, you're probably aware of the problem that the Iffley Lock measurement station is currently allegedly giving incorrect measurements because of debris obstructing the weir. However, I'm sceptical that Iffley would be dramatically different from what's happening at Osney and Sandford.

So, I wondered if we could look into a predictor for the Iffley readings based on the measurements from nearby locks, trained on the historical data we have (I'm guessing a simple linear regression might do well). And then use said prediction to give a new flow rate estimate.

**Comment by JoeHitchen** [comment]
Hi, all evidence (not just these graphs) seems to be suggesting that it is the bucks themselves which are an unreliable measure at the moment, rather than this data set or any of the sensors. Since four of the buck gates can't be closed at the moment, a reading of them will be high, but the obstructions are creating a hydrodynamic effect similar to them being closed.

_Standard disclaimer: Please make your own assessment of conditions before going out on the water_
